### ISSUE TITLE
Error opening application

### ISSUE THREAD

**Issue by YusukeUrameshiBR** [flathub/com.github.hluk.copyq#24]
Application does not open when clicking on it. Appears as running on the system monitor. Endless OS 3.8.5.

[gnome-software-verbose.txt](https://github.com/flathub/com.github.hluk.copyq/files/5081419/gnome-software-verbose.txt)
[eos-diagnostic-200816_172026_UTC-0400.txt](https://github.com/flathub/com.github.hluk.copyq/files/5081420/eos-diagnostic-200816_172026_UTC-0400.txt)

**Comment by hluk** [comment]
Can you run `flatpak run com.github.hluk.copyq`?

You can also try getting logs with `flatpak run com.github.hluk.copyq logs`.
