### ISSUE TITLE
App has 'Unverified' tag on Flathub, what makes it unavailable on Linux Mint

### ISSUE THREAD

**Issue by Ser-Bul** [flathub/com.github.hluk.copyq#65]
Having 'Unverified' tag means it's hidden from Software Manager search results on Linux Mint (https://www.phoronix.com/news/Linux-Mint-Unverified-Flatpaks)
@hluk, please perform the verification https://docs.flathub.org/docs/for-app-authors/verification

**Comment by hluk** [comment]
Thanks for the heads-up. Looking into it.

I think I need the access first: https://github.com/flathub/flathub/issues/5697

**Comment by hluk** [comment]
Done.
